version: '3.4'

services:
  sqlserver:
   environment:
    - "ACCEPT_EULA=Y"
    - "MSSQL_SA_PASSWORD=demoproject.3428"
   volumes:
   - sqlserver_volume:/var(opt/mssql)
   ports:
    - "1433:1433"
  demoproject:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "5000:8080"
      - "5001:8081"
    